"""Section 21's table: what seasonal-wildlife v7.1 builds from this study, finding by finding (1 Oct 2026).
Sources: the v7.1 stream notes (seasonal-wildlife branch v7.1 at fce7d68, docs/v7.1/<stream>.md), the lead's BUILD-PLAN.md,
the user's rulings R1-R63 (data/eco-review/part2/USER-REVIEW-PART2.md) and the Part 1 plan. Every row is built and untested:
nothing in v7.1 has run on the rig, and the validator has no v7.1 claims yet."""
from mdlite import inline

# (area, finding that drove it, what v7.1 builds, rulings, stream)
ROWS = [
    ("Apexes", "The apex FREQUENCY step gave what it was set to; the target was too low (S8, SW4)",
     "Apex step off the ladder; apex raw FREQUENCY capped at 5; an apex scheduler places apex groups from stock toward a presence target (20–30% of the season on land), at most 1 group on calm maps and 2 on savage ones",
     "R9, R34", "roster"),
    ("FREQUENCY ladder", "FREQUENCY is a relative weight per wave; groups differ in size (F1, X3, cluster sizes on the rig)",
     "The v2.2 ladder ported, with the pyramid targets as level totals; weights target units (divided by mean group size); a biomass guard; FREQUENCY never 0",
     "R57, R59", "roster"),
    ("Roster picks", "Animal people and giants are 49.3% of wildlife types; animal people were 37–44% of surface pools",
     "Pick weight animal people ×0.1 and GIANT_* ×0.2 (a slot only they can fill still fills); once seated, their FREQUENCY ×0.25 and ×0.5; the 19 animal people at FREQUENCY 0 get 1",
     "R13, R26, R61", "roster"),
    ("Roster layers", "v7.0's port had three layers and no flying layer; the temperate lake lacked an apex",
     "Flying layer with 1 raptor slot; ocean, lake and river tables; a curated water-apex list (the sea lamprey becomes a mesopredator); bears listed as fishers",
     "R43, R49, R50", "roster"),
    ("×3 pack bonus", "SW7 showed no effect, on a weak test",
     "Bonus kept; three defects fixed (it read a floored cluster midpoint, used a fixed seed, and gave animal people their root's cluster)",
     "R41", "roster"),
    ("Pelagics", "OCEAN2's pelagic slot came out empty",
     "Root cause fixed: ocean life rides land-layer entries, which the water roster never read. Pelagic slots on every ocean map; the column-depth survey reads every level (it stopped after the top one); prey present pulls predators into shallows, with a stranding guard one tick after placement",
     "R14, R59, R22", "roster, water"),
    ("Water groups", "SW6: BOATS got 2–5 water groups; the '2 per body' default had thin evidence",
     "Water bodies use the map-size cap like land, no fixed 2; Driver B's draw is weighted by what is swimming in that body now; failed draws retry",
     "R45, R62", "groups, water"),
    ("Groups at once", "Little's law held groups near 2–3 whatever the cap (ECO2-G, T8g)",
     "Every layer has its own cap, formula floor(√tiles)+1 or one fixed value (a toggle for slow computers); an adaptive release clock per layer aims at the cap with some randomness",
     "R7, R31", "groups"),
    ("Caverns", "v7.0's cavern cap trimmed only the tool's own groups; natives sat outside it (SW5)",
     "The tool gates every cavern layer at a fixed 5 groups, natives counted; the magma/underworld layer is never touched (demons unmanaged)",
     "R44, R60", "groups"),
    ("Animal people in caverns", "Plump helmet men arrived 54 and 180 a season on BOATS",
     "Animal-person group size capped at 5 in the caverns, lifted while that cavern irrupts",
     "R35", "groups"),
    ("Leaders", "Leaders held every kind of group; which member led made no consistent difference",
     "Leader = largest adult male; no male, no leader; a dead leader is not replaced and the herd, pack, school or pod panics; schools and pods need a wet leader; `place` makes one led group",
     "R32, C §9.3", "groups"),
    ("Placed packs", "The sweep's placed wolf pack was never a tracked group (SW1–SW2)",
     "`groups adopt <ids>` makes placed units one tracked, led group (the harness uses it)",
     "H3", "groups"),
    ("Solitary hunters", "Package ×2.1 in LONE/LONE10, order-confounded; SNEAK alone 1.75× (CI 0.44–8.2); the caste write was never read back",
     "Skill profiles 0–20 per species: solitary apex 15 (Legendary), pack baseline SNEAK 5, pack bonus 10; written to the caste NATURAL_SKILL and the unit, with a readback and the rust floor set",
     "R8, R40, R58", "ecology"),
    ("Ecology defaults", "SW1: cadence and nudge showed no effect (the nudge never fired)",
     "Ecology cadence 3,000; nudge off by default (still available)",
     "R37, R38", "ecology"),
    ("Raptors", "An eagle took ravens but never a rabbit (REACH)",
     "Raptors armed (BENIGN cleared), a small-prey cap, and a stoop that brings a raptor down beside related small land prey",
     "R47", "ecology"),
    ("Fishing", "Grizzlies, tigers and wolves never fished (FSH2, FISH)",
     "Bears fish by default: shore pairing, a walk to the bank, the school lured to the edge in its run season; polar bears swim to the fish and hunt on land too",
     "R33, R43", "ecology"),
    ("Cohesion table", "Solitary, pack and herd came from cluster size alone",
     "A whole-list solitary/pack/herd/flock/school table with per-species overrides, read by leaders, skills and pack detection",
     "R62", "ecology, fixes"),
    ("Scavenging pace", "The v7.0 pass cleared remains map-wide within ~2,400 ticks",
     "Natural cadence: a carcass is found after hours (sooner if large), only within perception range; scavengers walk; eating takes days of visits; a last-resort hop",
     "R18", "scav"),
    ("Swimmer scavengers", "Only pond grabbers, sea serpents and sea monsters qualified among swimmers",
     "Carnivorous swimmers scavenge, sharks, crocodiles and alligators included; who ate what is recorded",
     "R17, R42", "scav"),
    ("Rig scavenging verbs", "The rig fed wolves but not jackals, vultures or anything at the water (SCV, SCVW)",
     "Causes found: borrowed population refs, a one-shot eat, fliers that don't walk paths, water corpses a level below; the tool's pass handles each (re-issued walks, hops, bank reach)",
     "R16", "scav"),
    ("Curious beasts", "They leave because they stole; DF zeroes the countdown at the theft (CB)",
     "After a theft the tool clears that one unit's curious flags, resets its countdown to a natural stay and drops the loot; the species stays a thief",
     "R30", "scav"),
    ("Vermin", "Colony counts (14,000–19,000) are an industry size, never units on the map; DF wires one gobble class natively",
     "Vermin foraging on the vermin DF has on the map (colonies are weak attractors); GOBBLE_RULES plus the builder's edge table; SWV_COLONY and SWV_BAT classes",
     "R21, R27, R51", "vermin"),
    ("Extinct creatures", "Extinct apexes sit at FREQUENCY 50 (vanilla 2–5); 17 grazing dinosaurs lack GRAZER; four misfiled roles",
     "83 corrections applied on load and restored on unload: apex FREQUENCY 2–5, grazers, roles, clusters, realms; stands down where an installed mod covers the same thing",
     "R24", "extinct"),
    ("Depth guards", "The tool never read UNDERGROUND_DEPTH; `place` could put a magma crab on the surface",
     "Roster species only inside their raw depth; lava-only species beside magma or refused; `place` refuses the magma/underworld layer",
     "R28", "roster"),
    ("Water words", "'Depth' carried five meanings in the tool and the report",
     "Column depth (stacked tiles) and tile water level n/7 kept apart in code and output; `water depth` prints the histogram",
     "R22", "water"),
    ("Invasive species", "DF never drew the smilodon onto calm CTRL (INV2)",
     "Add invasive places a SAVAGE species itself on a calm map",
     "R36", "roster"),
    ("Irruption", "DF's invasions are disabled in its code; v7.0's irruption only flagged the next DF group",
     "IRRUPT v2: pressure per cavern layer (citizens, digging, breach, scarcity, season); warning, waves of the cavern's civ races from its own entries, end, cooldown; DF announcements; behaviour tokens on ~10% of each wave each, one unit with all; the cavern's non-civ animals agitated",
     "R4, R5, R6, R10", "irruption"),
    ("Controls", "The v7 switches were console-only",
     "One control registry (353 controls); the in-game Panel and the web companion both render it, with toggles, sliders and read-back",
     "R5, R7, R52, R54", "web, ui"),
    ("Performance", "Classification, groups and surveys were recomputed every pass",
     "P0–P13: per-job timing, memoized classification, groups and undo in cache, one census per pass, staggered jobs, native tile counts, sliced surveys; each change has a legacy switch",
     "R48, R55", "perf"),
    ("Known bugs", "Status lines that lied, spaced raw ids, stale caches, the web's cluster order",
     "Fixed, with the help text reconciled to the live verbs",
     "R56", "fixes"),
]


def table():
    head = "<thead><tr><th>Area</th><th>What the study found</th><th>What v7.1 builds</th><th>Rulings</th><th>Status</th></tr></thead>"
    body = "".join(
        f"<tr><td><b>{inline(a)}</b></td><td>{inline(f)}</td><td>{inline(b)}</td><td>{inline(r)}</td>"
        f"<td><span class='chip medium'>built, untested</span><br><span style='font:11.5px var(--mono);color:var(--ink3)'>{inline(s)}</span></td></tr>"
        for a, f, b, r, s in ROWS)
    return f"<table>{head}<tbody>{body}</tbody></table>"
