#!/usr/bin/env python3
"""Write examples2.md: concrete rosters per layer (main and savage configs)."""
from pathlib import Path
from roster2 import build, Cfg, SP
from dataclasses import replace

CASES = [('main', 'TEMP_GRASS_FOREST', 'land', 'SUMMER', 3), ('main', 'TAIGA_TUNDRA', 'land', 'WINTER', 5),
         ('main', 'TROP_SAVANNA_SHRUB', 'land', 'SPRING', 2), ('main', 'DESERT', 'land', 'AUTUMN', 1),
         ('main', 'TEMP_GRASS_FOREST', 'flying', 'SPRING', 1), ('main', 'TROP_WETLAND', 'flying', 'SUMMER', 2),
         ('main', 'OCEAN_SHORE', 'ocean', 'SUMMER', 1), ('main', 'OCEAN_SHORE_DEEP', 'ocean', 'SUMMER', 1),
         ('main', 'ARCTIC_COAST', 'ocean', 'WINTER', 3), ('main', 'TROP_OCEAN_SALTRIVER', 'river', 'SPRING', 4),
         ('main', 'LAKE_RIVER', 'lake', 'SUMMER', 2), ('main', 'LAKE_RIVER', 'river', 'SUMMER', 2),
         ('main', 'TROP_LAKE', 'lake', 'SPRING', 6), ('main', 'UNDER', 'cav1', 'SPRING', 1), ('main', 'UNDER', 'cav2', 'SPRING', 2),
         ('main', 'UNDER', 'cav3', 'SPRING', 3), ('main', 'UNDER', 'cavw1', 'SPRING', 1), ('main', 'UNDER', 'cavw2', 'SPRING', 4),
         ('main', 'UNDER', 'deep', 'SPRING', 1),
         ('savage', 'TEMP_GRASS_FOREST', 'land', 'SUMMER', 3), ('savage', 'TROP_SAVANNA_SHRUB', 'land', 'SPRING', 7),
         ('savage', 'DESERT', 'land', 'SPRING', 4), ('savage', 'TEMP_GRASS_FOREST', 'flying', 'SPRING', 1),
         ('savage', 'OCEAN_SHORE', 'ocean', 'SUMMER', 5)]
CF = {'main': Cfg(), 'savage': replace(Cfg(), savage=True, label='savage')}
MARK = {'df': '->', 'df?': '-?>', 'stock': '~>', 'no': '-x>'}

def tag(s):
    t = []
    if s.giant: t.append('giant')
    if s.sentient: t.append('sentient')
    if s.source == 'extinct': t.append('extinct')
    if s.benign: t.append('BENIGN')
    if s.cb: t.append('curious')
    if s.cmax > 1: t.append('grp %d:%d' % (s.cmin, s.cmax))
    return ', '.join(t)

out = ['# roster2 example rosters (generated by examples2.py)\n',
       'Edge marks: `->` DF carries it out (measured pattern), `-?>` written but reach untested on the rig, `~>` vermin stock '
       'transfer done by the tool, `-x>` BENIGN attacker (DF will not act). Share = arrival share implied by the frequency ladder '
       '(F1: DF picks in proportion to FREQUENCY).\n']
for lb, e, l, s, sd in CASES:
    r = build(e, l, s, sd, CF[lb])
    out.append('## %s | %s | %s | %s | seed %d  (pool %d, %d species, %d edges)\n' % (lb, e, l, s, sd, r['pool_n'], len(r['roster']), len(r['edges'])))
    if not r['roster']:
        out.append('(empty: no linked candidate in the pool)\n'); continue
    out.append('| species | slot | tags | ladder f | share |')
    out.append('|---|---|---|---|---|')
    for sid in r['roster']:
        out.append('| %s | %s | %s | %s | %s |' % (sid, r['slot'][sid], tag(SP[sid]), r['freq'].get(sid, 'stock'), r['share'].get(sid, '')))
    out.append('')
    out.append('Edges: ' + '; '.join('%s %s %s (w %.2f)' % (a, MARK[ac], b, w) for a, b, w, k, ac in r['edges']))
    extra = []
    if r['benign_clear']: extra.append('BENIGN cleared: ' + ', '.join(r['benign_clear']))
    if r['season_break']: extra.append('NO_<season> writes: ' + ', '.join('%s %s' % x for x in r['season_break']))
    if r['cb_resident']: extra.append('curious beasts (leave in ~3,000 t unless flags off): ' + ', '.join(r['cb_resident']))
    if r['repaired'] or r['dropped']: extra.append('repair: %s dropped: %s' % (r['repaired'], r['dropped']))
    extra.append('stop list (entry quantity 0): %d species' % len(r['stop']))
    out.append('\n' + '. '.join(extra) + '.\n')
Path(__file__).with_name('examples2.md').write_text('\n'.join(out))
