#!/usr/bin/env python3
"""Concrete example rosters per failure mode -> examples.md"""
from analyze import *   # noqa
from run import CONFIGS
out = []; P = out.append
def show(r):
    E = [tuple(e) for e in r['edges_final']]
    tag = lambda i: i + ('*' if SPECIES[i].benign and is_eater(SPECIES[i], CONFIGS[r['cfg']]) and not SPECIES[i].vermin else '')
    return ('- `%s / %s / %s / seed %d` seed=**%s**  \n  roster: %s  \n  edges: %s' % (r['bkey'], r['layer'], r['season'], r['seed'], r['seed_sp'],
            ', '.join('%s (%s)' % (tag(i), r['classes'][i]) for i in r['roster']), ' · '.join('%s>%s' % e for e in E) or '(none)'))
def first(R, cfg, pred, n=1):
    got = []
    for r in R:
        if r['roster'] and pred(r, derive(r, cfg)): got.append(r)
        if len(got) >= n: break
    return got
B = CONFIGS['baseline']; R = load('baseline')
cases = [
 ('Size bands demote LP cats/bears to "small predator": rule B makes a cougar eat beetles and slugs; an AP (grizzly man) is the web\'s top predator',
  lambda r, d: 'COUGAR' in r['roster'] and 'BEAR_GRIZZLY_MAN' in r['roster']),
 ('Wolf pack: rule B + F (+1) -> wolves eat vermin and "small" prey; the 140k deer counts as small',
  lambda r, d: 'WOLF' in r['roster'] and r['layer'] == 'land'),
 ('Singleton roster: HV seed is a 2M cm3 giant insect no flier may eat (rule E caps giant raptors at medium prey; B caps raptors at vermin)',
  lambda r, d: len(r['roster']) == 1 and r['layer'] == 'flying'),
 ('Cavern singleton: DRALTHA/RUTHERER (>=1M) seeds; nothing may eat large prey without a pack (E "medium to small")',
  lambda r, d: len(r['roster']) == 1 and r['layer'].startswith('cav')),
 ('Rule D: cavern sentients (troglodyte, rodent man, amphibian man...) have no allowed eater; they sit in the web as uneaten predators',
  lambda r, d: d['sentient_uneaten'] and r['layer'].startswith('cav')),
 ('Rule C in caverns: cave swallow / bat vermin are eaters with no flying insects to eat',
  lambda r, d: d['vbird_no_insect'] and r['layer'].startswith('cav')),
 ('Seasonal break: bird vermin whose only prey (moth/butterfly/firefly) is NO_WINTER',
  lambda r, d: d['season_break']),
 ('Flying layer: every predator edge is BENIGN (marked *) -> DF will not act on any of them',
  lambda r, d: r['layer'] == 'flying' and r['edges_df_feasible'] == 0 and r['edges_unit'] > 0),
 ('Deep layer: the same two species every seed', lambda r, d: r['layer'] == 'deep'),
 ('Step 8 fails although the web is connected (no pack predator with prey)', lambda r, d: not r['step8'] and r['components'] == 1 and r['layer'] == 'land'),
]
P('# Example rosters (generated by examples.py). `*` = BENIGN eater (DF never acts on its relation).\n')
P('## Baseline (rules as written)\n')
for title, f in cases:
    P('### ' + title + '\n')
    for r in first(R, B, f): P(show(r))
    P('')
for lb in ('FIX3', 'FIX3_ratio'):
    P('## %s: same cells\n' % lb)
    Rf = load(lb); cfg = CONFIGS[lb]
    for key in [('TEMP_GRASS_FOREST', 'land', 'SPRING', 1), ('TEMP_GRASS_FOREST', 'land', 'WINTER', 2), ('OCEAN_SHORE', 'water', 'SUMMER', 1),
                ('TEMP_GRASS_FOREST', 'flying', 'SPRING', 1), ('UNDER', 'cav1', 'SPRING', 1), ('UNDER', 'cav3', 'SPRING', 1), ('TROP_WETLAND', 'flying', 'SPRING', 3)]:
        r = next(x for x in Rf if (x['bkey'], x['layer'], x['season'], x['seed']) == key)
        P(show(r))
    P('')
(HERE / 'examples.md').write_text('\n'.join(out) + '\n')
print('\n'.join(out))
